blank_issues_enabled: false
contact_links:
  - name: Discord Support Server
    url: https://discord.gg/yZGanTPdPF
    about: If you need help regarding RedditVanced or plugins, please join the support server!